### ISSUE TITLE
Implementing IDE in browser using Datalog

### ISSUE THREAD

**Issue by safinaskar** [voodoos/mlts#22]
IDE in browser with usual IDE features ("go to definition" etc). In Datalog (similar to Lambda-Prolog).

See here: https://github.com/astampoulis/makam/issues/118 . Also advertising ideas

**Comment by safinaskar** [comment]
Dual issue: https://github.com/vilterp/datalog-ts/issues/374

**Comment by voodoos** [comment]
As is, this issue looks like spam. If you want to report an issue or suggest an improvement please articulate you thoughts, we should not have to follow links to understand what you mean.

Also note that this repository has been inactive for some time now and I have no plans to work on this repository on the near future. External contributions are welcome.

**Comment by safinaskar** [comment]
I'm just pointing to similar project ( https://petevilter.me/post/datalog-typechecking/ ) in hope it will be interesting. I'm sorry for misunderstanding
